.github/workflows/pr_check.yml

Change the target branch name from `staging` to `develop` on pr_check.yml.

Change the target branch name from staging to develop on pr_check.yml

---

Dockerfile
README.md
docker-compose.yml
package.json

Changed the docker-compose settings of the mock server
Please run on your environment
None

fix: change the mock server strategy

---

docker-compose.yml

fixed reference to web-api. it was not latest.

fix: reference to web-api fix

---

package-lock.json
package.json
src/components/ui/Dialog.tsx
src/components/ui/DialogUsageExample.tsx
src/components/ui/index.ts
tailwind.config.ts

This pull request introduces the Dialog component based on [shadcn/ui](https://ui.shadcn.com/docs/components/dialog).
1. Ran `npx shadcn-ui@latest add dialog`, and a pre-made dialog component was generated.
2. Adjusted the styles using Tailwind CSS classes.
3. Configured some animations in the `tailwind.config.ts and adjusted the animations of the dialog as well.`
4. Added the `Body` part to the dialog component.
- I created the example component as well. Please utilize it for your review. It is planned to be deleted once the first dialog is implemented.
https://github.com/genesis-tech-tribe/nishiki-frontend/assets/99148565/b961bbd8-52a7-4583-8341-ff03af43f1ca

feat: create dialog component based on shadcn

---

src/components/page/GroupSingle.tsx
src/components/page/GroupsPage.tsx
src/features/groups/components/ContainerCount.tsx
src/features/groups/components/ContainerList.tsx
src/features/groups/components/GroupItem.tsx
src/features/groups/components/GroupList.tsx
src/features/groups/components/MemberList.tsx
src/features/groups/components/UserCount.tsx

Fix default export to Named Exports at react component

---

src/components/ui/Button.tsx

I have made changes across the repository by replacing all the wildcard imports with named imports.

Wildcard to named import

---

src/components/page/GroupSingle.tsx
src/components/page/GroupsPage.tsx

- use arrow method for page component

use arrow method for page component

---

src/components/page/GroupsPage.tsx
src/features/groups/components/ContainerList.tsx
src/features/groups/components/GroupItem.tsx
src/features/groups/components/GroupList.tsx
src/features/groups/components/MemberList.tsx
src/lib/api/data.ts
src/types/definition.ts

- refactored definition.ts path

refactor: definition.ts path

---

docs/STYLEGUIDE.md

This pull request adds a `STYLEGUID.md` file that documents code styling rules. Rules can be updated or added anytime in the future.
- Please let me know if you would like me to add some rules now.

Created `STYLEGUIDE.md`

---

.eslintignore
.husky/commit-msg
.husky/prepare-commit-msg
commitlint.config.js
docs/CONTRIBUTING.md
package-lock.json
package.json

This PR introduces [`commitlint`](https://commitlint.js.org/#/) and [`commitizen`](https://commitizen.github.io/cz-cli).
- Installed and set up `commitlint`, following the [official setup instruction](https://commitlint.js.org/#/guides-local-setup).
- Installed and set up `commitizen`, following the [official document](https://commitizen.github.io/cz-cli)
- Updated the "Commit Convention" section of `CONTRIBUTING.md` because some prefixes were missing.
- You can confirm that `commitlint` works by executing (expected to fail):
```bash
git commit -m "foo: this will fail" --allow-empty
```
- You can confirm that `commitizen` works by running the regular `git commit` command (See the video below)
How `commitizen` works:
https://github.com/genesis-tech-tribe/nishiki-frontend/assets/99148565/380 …

Feat: Set up commitlint & commitizen

---

tailwind.config.ts

- Modified tailwind fontsize setting to be extended not be overwritten

tailwind.config.ts, make fontsize inside of extend curly brackets

---

src/app/groups/[id]/members/page.tsx
src/components/page/MembersPage.tsx

This PR implements members route
- Created `src\app\groups\[id]\members\page.tsx`

Feat: Create members route

---

src/app/groups/[id]/members/page.tsx
src/components/page/MembersPage.tsx

This PR implements fetching and displaying members list

Feat: Fetch and display members list

---

src/components/ui/Button.tsx
src/components/ui/DatePicker.tsx
src/components/ui/DialogUsageExample.tsx
src/components/ui/DrawerUsageExample.tsx
src/components/ui/SelectUsageExample.tsx
src/components/ui/SelectionDrawer/SelectionDrawerUsageExample.tsx

This PR responsibility is to only change the default values (for `variant` and `size`) of the `Button` component to "none".
- I made this change because I thought it was very weird to specify 'none' when no styles are needed. 
- This PR has no associated issues.

Refactor: Change the default values of the Button component to "none"

---

.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/problem.md
.github/ISSUE_TEMPLATE/task.md

This PR refines the existing issue templates by removing unnecessary parts.
- Removed the default title because sometimes to prevent from forgeting to modify it.
- Removed the "additional contexts" section because we sometimes forget to delete it when there is no additional context. "Additional Contexts" is a generic title and cannot be used as is.
-

Docs: Remove unnecessary parts in the issue templates

---

src/lib/api/containerApiClient.ts
src/lib/api/groupApiClient.ts
src/lib/api/index.ts

- Refactored to divide contents in `groupApiClient.ts`
- divide codes in `groupApiClient.ts` into `groupApiClient.ts` and `containerApiClient.ts`
- Whether the code is well organized or not.
- NA

Refactor: divide contents in groupApiClient.ts

---

.github/pull_request_template.md

This PR adds the "References" section to the `pull_request_template.md`. In that section, assignees should try to include the links to the references they have used to complete the task.
- Added the "References" section
- Added check items to each checklist (*Additional)
- Aligned the conventions of the writing in the checklist (*Additional)

Docs: Add "References" section to the PR template

---

src/features/foods/components/Form/AddDrawerContent/AddDrawerBody.tsx
src/features/foods/components/Form/CategorySelect.tsx
src/features/foods/components/Form/EditDrawerContent/EditDrawerBody.tsx

Please see the issue this PR is based on: #175 
- This is a temporary alteration, and this part will be modified again shortly in one of the following PRs.
- https://github.com/genesis-tech-tribe/nishiki-frontend/pull/165
- https://github.com/genesis-tech-tribe/nishiki-frontend/pull/167
- I will merge this PR once only one review approves it.

Refactor: Define state of selected category out of CategorySelect

---

src/features/groups/components/CreateGroupButton/CreateGroupDrawerContent.tsx
src/features/groups/components/CreateGroupButton/action.ts
src/lib/api/commonUtils.ts

feat: added sample code

---

src/components/ui/Input/NumberInput.tsx

Please see the linked issue: #178 
This modification is required to complete the following PRs:
- #165 
- #167
- You can check if it works fine by trying the existing `NumberInput` on the browser.

Refactor: Update the `NumberInput` component using `forwardRef`

---

src/features/groups/components/CreateGroupButton/CreateGroupDrawerContent.tsx
src/features/groups/components/CreateGroupButton/index.tsx
src/lib/api/group/client/groupApiClient.client.ts

- Implement `Form` component in `CreateGroupDrawerContent`.
- Replaced pure html `form` tag with common `Form` component.
- if `Form` logic with react-hook-form is properly implemented
- I separated Form logic from `CreateGroupButton` component, which made me pass `isOpen` and `onClose` props to `CreateGroupContentDrawer`. If it seems like unnecessary props to you, we can also consider putting everything in `CreateGroupButton` .
https://github.com/genesis-tech-tribe/nishiki-frontend/assets/99339182/157a8568-1ea6-4255-9022-2a453321c81f

Feat : utilize `Form` component to create group form

---

src/components/page/GroupSingle.tsx
src/features/groups/components/ContainerList.tsx
src/features/groups/components/MemberList.tsx

- Apply group single page design
- Applied design at group single page.
- Added Link to memberlist page, foodlist page
- Function is not implemented at this PR.

Feat: Apply group single page design

---

.github/pull_request_template.md
docker-compose.yml

Updated the old organization names that existed in the code.

Chore: Rename the organization name

---

src/components/ui/FormUsageExample.tsx
src/features/foods/components/BadgeList/index.tsx
src/features/foods/components/FilterButton/index.tsx
src/features/foods/components/FoodSort.tsx
src/features/foods/components/SearchBar.tsx
src/features/foods/types/FoodTypes.ts
src/features/foods/utils/containerMapping.ts
src/features/groups/components/CreateGroupButton/CreateGroupDrawerContent.tsx
src/lib/api/common/client/commonUtils.client.ts
src/lib/api/common/server/commonUtils.server.ts
src/lib/api/container/server/containerApiClient.server.test.ts
src/lib/api/container/server/containerApiClient.server.ts
src/lib/api/group/client/groupApiClient.client.test.ts
src/lib/api/group/client/groupApiClient.client.ts
src/lib/api/group/server/groupApiClient.server.test.ts
src/lib/api/group/server/groupApiClient.server.ts
src/lib/api/user/server/userApiClient.server.test.ts
src/lib/api/user/server/userApiClient.server.ts
src/middleware.ts
src/types/definition.ts

Fixes #214
Remove types from tsdoc.

Docs: Remove types from tsdoc

---

.github/pull_request_template.md
docs/CONTRIBUTING.md

This PR adds new branch types (refactor, fix, test) and updates the prefix rules for PR titles to match one of the branch types.
- Added the following branch types to the "Types of Branches" section of `CONTRIBUTING.md`
- refactor
- fix
- test
- Updated the prefix rules for PR titles to match one of the branch types
- Please take a look at the reference below to know how I came up with new branch type names.
- [Chat History with ChatGPT](https://chat.openai.com/share/e893121b-a94d-419b-8e65-a0a6afc1f995)
- This PR is not based on any issue.

Docs: Add new branch types and update prefix rules for PR titles

---

package-lock.json
package.json
src/components/page/LoginPage.tsx
src/components/ui/Dialog.tsx

I changed the position of DialogClose from PrimitiveContent to DialogHeader so that it is properly aligned in the center.
- Moved DialogClose to DialogHeader
- Enclosed the div in DialogHeader in a parent div and added DialogClose as the sibling
- Your instructions said that "The component structure and styles of DrawerHeader in src/components/ui/Drawer.tsx should be similar," however, I didn't need to make any changes there.

Feature: Adjust the position of the close [ x ] button of the Dialog component

---

src/components/ui/FormUsageExample.tsx
src/features/foods/components/Form/AddDrawerContent/index.tsx
src/features/foods/components/Form/EditDrawerContent/index.tsx

This PR fixes the unscrollable drawer body.
- Added `overflow-y-auto` to every `form` tag that causes the layout to collapse.
- 
https://github.com/nishiki-tech/nishiki-frontend/assets/99148565/3bb58ef9-a407-4991-8592-604ca3dabb15
-
- Although the DrawerFooter was stuck to the bottom edge in the previous state, I changed and included it into the scrollable area as per the design.
Here is the design I referenced:

Fix: Fix unscrollable drawer

---

src/features/foods/lib/actions.test.ts
src/features/foods/lib/actions.ts
src/features/foods/lib/schema.ts

- Added a validation to the DELETE food
- Revised the ID validation on  food CREATE and UPDATE
-

Feature: Add validation to the DELETE food

---

src/features/groups/components/GroupCardList/GroupCard/GroupCardContent/GroupCardDropdownMenuTriggerButton/GroupCardDropdownMenuContent/DeleteGroupDialogTriggerButton/DeleteGroupDialogContent.tsx
src/features/groups/components/GroupCardList/GroupCard/GroupCardContent/GroupCardDropdownMenuTriggerButton/GroupCardDropdownMenuContent/DeleteGroupDialogTriggerButton/index.tsx
src/features/groups/components/GroupCardList/GroupCard/GroupCardContent/GroupCardDropdownMenuTriggerButton/GroupCardDropdownMenuContent/index.tsx
src/features/groups/components/GroupCardList/GroupCard/GroupCardContent/GroupCardDropdownMenuTriggerButton/index.tsx
src/features/groups/components/GroupCardList/GroupCard/GroupCardContent/index.tsx
src/features/groups/lib/actions.test.ts
src/features/groups/lib/actions.ts
src/features/groups/lib/schemas.ts
src/lib/api/group/client/groupApiClient.client.test.ts
src/lib/api/group/client/groupApiClient.client.ts
src/lib/api/group/client/index.ts

Implement delete group API client and action. Applied it to `DeleteGroupDialog` component
- Add Delete group API client and refactor existing code in [src/lib/api/group/client/groupApiClient.client.ts](https://github.com/nishiki-tech/nishiki-frontend/pull/282/files#diff-eb437d2e48a181934f57ecc6a8ea1a56ef9d37d44816a17587e744023772f9a2)
- Add Delete group action to and refactor existing code in [src/features/groups/lib/actions.ts](https://github.com/nishiki-tech/nishiki-frontend/pull/282/files#diff-cbbd8050cd0522718c2b39af6e9a9b344061c34b347e651528e8b7ea537936ab)
- Apply action function to [src/features/groups/components/GroupCardList/GroupCard/GroupCardContent/GroupCardDropdownMenuTriggerButton/GroupCardDropdownMenuContent/DeleteGroupDialogTriggerButton/DeleteGroupDialogContent.tsx](https:/ …

Feat : implement delete group api client

---

src/features/foods/components/DeleteFoodDialogContent.tsx
src/features/groups/components/ContainerCardList/ContainerCard/ContainerCardDropdownMenuTriggerButton/ContainerCardDropdownMenuContent/DeleteContainerDialogTriggerButton/DeleteContainerDialogContent.tsx
src/features/groups/components/ContainerCardList/ContainerCard/ContainerCardDropdownMenuTriggerButton/ContainerCardDropdownMenuContent/DeleteContainerDialogTriggerButton/index.tsx
src/features/groups/components/ContainerCardList/ContainerCard/ContainerCardDropdownMenuTriggerButton/ContainerCardDropdownMenuContent/index.tsx
src/features/groups/components/ContainerCardList/ContainerCard/ContainerCardDropdownMenuTriggerButton/index.tsx
src/features/groups/components/GroupCardList/GroupCard/GroupCardContent/GroupCardDropdownMenuTriggerButton/GroupCardDropdownMenuContent/DeleteGroupDialogTriggerButton/DeleteGroupDialogContent.tsx
src/features/groups/components/InviteMemberDialog/InviteMemberDialogContent.tsx

Implement the delete container dialog
- move delete button `DropdownMenuButton` to different component named `DeleteContainerDialogTriggerButton` this is same structure as Group dropdown menu.
- as I talked with @nick-y-ito , we don't need 
```tsx
const handleCancel = () => {
closeParentOnCancel && onParentClose?.();
};
```
for deleteing Group/Container, so I deleted this from `DeleteGroupDialogContent.tsx`. I would like you to review if it is OK, I checked by myself and it is correctly working, but to make sure.
- I changed some code in some file which is not target scope of this PR, please ignore that part, I left some comment ,which you can ignore
[DeleteContainer_UI.webm](https://github.com/nishiki-tech/nishiki-frontend/assets/142355969/e4b3dd40-47be-454a-8aae-93987f58e902)

Feature: Delete container UI in group single page

---

src/components/parts/BottomMenuLink.tsx

Fix the issue where one of the bottom icons is not highlighted on the "group single" and "members" pages.
https://github.com/nishiki-tech/nishiki-frontend/assets/99148565/2cf49196-f7ec-408e-94e1-38dec57b911d

Fix: Highlight the bottom icons on sub pages

---

.husky/pre-push

This PR adds the `pre-push` hook that runs `npm test`
- I have added the file and the script by running this command:
```bash
npx husky add .husky/pre-push "npm test"
```
https://github.com/nishiki-tech/nishiki-frontend/assets/99148565/ebd4791c-a538-4b7a-a4e4-265de1cb240b

Chore: Add pre-push hook to run test

---

package-lock.json
package.json
src/app/layout.tsx

This PR sets up Vecel monitoring.
Please see the associated issue.
- https://vercel.com/docs/analytics/quickstart#add-the-analytics-component-to-your-app
- https://vercel.com/docs/speed-insights/quickstart#add-the-speedinsights-component-to-your-app
-

Feature: Set up Vecel monitoring

---

src/components/pages/FoodsPage.tsx
src/features/foods/components/FoodSort.tsx

Remove meatball button and add truncate to sort button
https://github.com/nishiki-tech/nishiki-frontend/assets/99148565/2bce0047-b23a-40d4-86cf-1efaf45f5667
-
-

Fix: Remove meatball button and add truncate to sort button

---

src/components/pages/ProfilePage.tsx
src/lib/api/auth/server/authApiClient.server.test.ts
src/lib/api/auth/server/authApiClient.server.ts
src/lib/api/user/server/index.ts
src/lib/api/user/server/userApiClient.server.test.ts
src/lib/api/user/server/userApiClient.server.ts

This PR is aiming to fix the PR, following the change in backend with the issue #255.
Only `auth/me` and `users/{:userId}` API client are fixed, and the one for generating invitation link still remains unresolved.
- Fix API response type to use in `getCurrentUserId` method 
- Fix API response type to use in `getUserById` method
- Fix corresponding tests
- Apply the change to `ProfilePage`

Fix: Fix `auth/me` and `users/{:userId}` API

---

src/features/groups/components/InviteMemberDialog/InviteMemberDialogContent.tsx
src/lib/api/group/client/groupApiClient.client.test.ts
src/lib/api/group/client/groupApiClient.client.ts

modify the response type of  `putGenerateInvitationLinkHash` function
- change the return type from string to object

Fix: Modify return type of generate invitation link

---

LICENSE
README.md

This PR aims to add an OSS license to this repository.
- Added the `LICENSE` file to the root directory
- Added the License section to `README.md`
- Added the Nishiki logo to the bottom of `README.md` (extra)
I have added in this flow:
<br>
- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#determining-the-location-of-your-license
-

Docs: Add License

---

.eslintignore
package.json
scripts/setupEnv.mjs

This PR fixes issue #338, which causes sign-in failure.
- Created `scripts/setupEnv.mjs`
- Modified the `postinstall` script in `package.json`
- I have confirmed that the creation of `.env.development.local` file was skipped correctly on my Vercel account.
- [Vercel - System Environment Variables Overview](https://vercel.com/docs/projects/environment-variables/system-environment-variables)
- [Vercel - Environment Variable Load Order](https://nextjs.org/docs/app/building-your-application/configuring/environment-variables#environment-variable-load-order)
- [Vercel - Environment Variable Load Order](https://nextjs.org/docs/app/building-your-application/configuring/environment-variables#environment-variable-load-order)
> ## Environment Variable Load Order
> Environment variables are looked up …

Fix: Fix signin problem on Vercel Preview environment

---

README.md

Please take a look at the associated issue.
-

Fix: Fix the path to the app screenshots files

---

src/app/layout.tsx
src/const/appConst.ts

This PR fixes the waring that says "specify metadataBase" in the server console.
The warning no longer persists.
- [Next.js - metadataBase](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase)
-

Fix: Add metadataBase to fix the console waring

---

.github/dependabot.yml

Introduces dependabot configuration.
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
- I purposely set the interval to `daily` to get quick feedback. Once we get used to it, we can set it to either `weekly` or `monthly`
- If we receive too many PRs, consider adding [`groups`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) option

Chore: Add dependabot configuration
